language: scala
scala:
  - "2.11.4"
jdk:
  - oraclejdk7
script: (if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then (echo "Only building pull requests - build passed."; exit 0); else sbt "++ ${TRAVIS_SCALA_VERSION} ; test"; fi)
branches:
  only:
    - master

